[project]
name = "dotfiles"
revision = "1.0"

[providers]
dotenv = "dotenv:.env.dotfiles" # Store the `OP_SERVICE_ACCOUNT_TOKEN` here. This should be a readonly token account.
keyring = "keyring://"
op-token = { uri = "op+token://Development/Dotfiles", depends_on = [
	{ secret = "OP_SERVICE_ACCOUNT_TOKEN" },
] }

[profiles.default.defaults]
providers = ["op-token"]
required = true

[profiles.default.OP_SERVICE_ACCOUNT_TOKEN]
description = "1Password service account token for automated access"
providers = ["dotenv", "keyring"]

[profiles.default.GITHUB_TOKEN]
description = "GitHub personal access token for gh CLI and API access"
providers = [{ provider = "op-token", path = ["forges"] }]

[profiles.default.NIX_GITHUB_TOKEN]
description = "GitHub personal access token for gh CLI and API access"
providers = [{ provider = "op-token", path = ["nix"], key = "GITHUB_TOKEN" }]

[profiles.default.GOOGLE_API_KEY]
description = "Google API key"
providers = [{ provider = "op-token", path = ["google"] }]

[profiles.default.OPENAI_API_KEY]
description = "OpenAI API key for GPT models and Codex"
providers = [{ provider = "op-token", path = ["ai"] }]

[profiles.default.OLLAMA_CLOUD_API_KEY]
description = "ollama cloud API token"
providers = [{ provider = "op-token", path = ["ai"] }]

[profiles.default.HUGGING_FACE_TOKEN]
description = "HuggingFace api token for model access"
providers = [{ provider = "op-token", path = ["ai"] }]

[profiles.default.XIAOMI_MIMO_API_KEY]
description = "xiaomi api token for model access"
providers = [{ provider = "op-token", path = ["ai"] }]

[profiles.default.PULUMI_TOKEN]
description = "Pulumi access token for infrastructure management"
providers = [{ provider = "op-token", path = ["infra"] }]

[profiles.default.NPM_TOKEN]
description = "npm registry publish token"
providers = [{ provider = "op-token", path = ["registries"] }]

[profiles.default.CARGO_REGISTRY_TOKEN]
description = "crates registry publish token"
providers = [{ provider = "op-token", path = ["registries"] }]

[profiles.default.FLAKEHUB_TOKEN]
description = "FlakeHub token for Nix flake publishing"
providers = [{ provider = "op-token", path = ["registries"] }]

[profiles.default.DISCORD_CLIENT_ID]
description = "Discord application client ID"
providers = [{ provider = "op-token", path = ["discord"] }]

[profiles.default.DISCORD_CLIENT_SECRET]
description = "Discord application client secret"
providers = [{ provider = "op-token", path = ["discord"] }]

[profiles.default.BACKBLAZE_KEY_ID]
description = "The Backblaze key id"
providers = [{ provider = "op-token", path = ["backblaze"] }]

[profiles.default.BACKBLAZE_KEY_NAME]
description = "The Backblaze key name"
providers = [{ provider = "op-token", path = ["backblaze"] }]

[profiles.default.BACKBLAZE_APPLICATION_KEY]
description = "The Backblaze application key"
providers = [{ provider = "op-token", path = ["backblaze"] }]
