#!/usr/bin/env bash
set -euo pipefail

GIT_CONFIG_DIR="$HOME/.config/git"
GIT_CONFIG_FILE="$HOME/.gitconfig"

mkdir -p "$GIT_CONFIG_DIR"

touch "$GIT_CONFIG_FILE"

python3 - <<'PY'
from pathlib import Path
import re

config_path = Path.home() / '.gitconfig'
start_marker = '### AUTOGENERATED ifiokjr/dotfiles'
end_marker = '### END_AUTOGENERATED ifiokjr/dotfiles'
expected = f"""{start_marker}
# Include a separate file for the default configuration
[include]
    path = ~/.config/git/main
# Include a separate file for aliases
[include]
    path = ~/.config/git/aliases
{end_marker}
"""

content = config_path.read_text() if config_path.exists() else ''
normalized = content.lstrip('\n')
pattern = re.compile(
    rf'{re.escape(start_marker)}\n.*?\n{re.escape(end_marker)}\n?',
    re.DOTALL,
)
remaining = pattern.sub('', normalized, count=1).lstrip('\n')

if normalized.startswith(expected) and remaining == normalized[len(expected):].lstrip('\n'):
    raise SystemExit(0)

config_path.write_text(expected + ('\n' + remaining if remaining else ''))
PY

echo "Ensured ~/.gitconfig includes the managed ~/.config/git includes block"

# Configure the local git hooks path so pre-commit/pre-push hooks are active
# in this dotfiles repository only (not globally).
REPO_HOOKS_DIR="$HOME/.dotfiles/.githooks"
if [ -d "$REPO_HOOKS_DIR" ]; then
	git -C "$HOME/.dotfiles" config core.hooksPath "$REPO_HOOKS_DIR"
	echo "Set local core.hooksPath to $REPO_HOOKS_DIR for dotfiles repo"
else
	echo "⚠  $REPO_HOOKS_DIR not found — skipping local hooksPath setup"
fi
