#!/usr/bin/env bash
set -euo pipefail

GIT_CONFIG_DIR="$HOME/.config/git"
GIT_CONFIG_FILE="$HOME/.gitconfig"

mkdir -p "$GIT_CONFIG_DIR"

touch "$GIT_CONFIG_FILE"

START_MARKER="### AUTOGENERATED ifiokjr/dotfiles"
END_MARKER="### END_AUTOGENERATED ifiokjr/dotfiles"
TEMP_CONFIG="$(mktemp)"

cat >"$TEMP_CONFIG" <<EOF
$START_MARKER
# Include a separate file for the default configuration
[include]
    path = ~/.config/git/main
# Include a separate file for aliases
[include]
    path = ~/.config/git/aliases
$END_MARKER
EOF

awk \
	-v start_marker="$START_MARKER" \
	-v end_marker="$END_MARKER" '
		$0 == start_marker { skipping = 1; next }
		$0 == end_marker { skipping = 0; next }
		skipping == 0 { print }
	' "$GIT_CONFIG_FILE" | sed '/./,$!d' >>"$TEMP_CONFIG"

mv "$TEMP_CONFIG" "$GIT_CONFIG_FILE"

echo "Ensured ~/.gitconfig includes the managed ~/.config/git includes block"

# Configure the local git hooks path so pre-commit/pre-push hooks are active
# in this dotfiles repository only (not globally).
REPO_HOOKS_DIR="$HOME/.dotfiles/.githooks"
if [ -d "$REPO_HOOKS_DIR" ] && git -C "$HOME/.dotfiles" rev-parse --git-dir >/dev/null 2>&1; then
	git -C "$HOME/.dotfiles" config core.hooksPath "$REPO_HOOKS_DIR"
	echo "Set local core.hooksPath to $REPO_HOOKS_DIR for dotfiles repo"
else
	echo "⚠  $HOME/.dotfiles is not a git checkout with $REPO_HOOKS_DIR — skipping local hooksPath setup"
fi
