allowBuilds:
  "@google/genai": true
  core-js: true
  keytar: true
  koffi: true
  node-pty: true
  opencode-ai: true
  protobufjs: true
  re2: true
  tree-sitter-bash: true
minimumReleaseAgeExclude:
  - opencode-linux-x64-baseline-musl@1.18.19
  - opencode-linux-x64-musl@1.18.19
  - opencode-linux-x64@1.18.19
