allowBuilds:
  "@google/genai": true
  core-js: true
  esbuild: set this to true or false
  keytar: true
  koffi: true
  node-pty: true
  opencode-ai: true
  protobufjs: true
  re2: true
  tree-sitter-bash: true
minimumReleaseAgeExclude:
  - opencode-linux-x64-baseline-musl@1.18.19
  - opencode-linux-x64-musl@1.18.19
  - opencode-linux-x64@1.18.19
  - '@voidzero-dev/vite-plus-core@0.3.1'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.3.1'
  - '@voidzero-dev/vite-plus-darwin-x64@0.3.1'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.1'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.3.1'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.3.1'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.3.1'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.1'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.3.1'
  - vite-plus@0.3.1
