exclude = [
	"**/dist/**",
	"docs/book/**",
	".devenv/**",
	".tmp-node/**",
	"**/fixtures/**",
	"fixtures/**",
	"**/snapshots/**",
	"**/target/**",
	"**/node_modules/**",
	".bin/**",
	"**/*.toml.template",
]

[formatting]
align_comments = false
align_entries = false
array_auto_collapse = false
array_auto_expand = true
array_trailing_comma = true
column_width = 100
compact_arrays = true
compact_entries = false
compact_inline_tables = false
indent_entries = false
indent_string = "\t"
indent_tables = false
inline_table_expand = false
reorder_arrays = false
reorder_inline_tables = false
reorder_keys = false
trailing_newline = true
allowed_blank_lines = 1

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "build-dependencies", "workspace.metadata.bin"]

[rule.formatting]
reorder_keys = true
