#!/usr/bin/env bash
set -euo pipefail

# Rebuild system configuration after nix config changes.
# This hook inlines the rebuild logic in bash so it does not depend on nushell
# (which may have been removed from the nix profile moments before).
echo "Rebuilding system configuration..."

# Source nix environment if available (needed when hook runs in a fresh shell,
# e.g. during setup where the parent process has nix in PATH but child doesn't)
if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
	# shellcheck disable=SC1091
	. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

# Also add user nix profile to PATH (for nix profile-installed tools like nu)
if [ -d "$HOME/.nix-profile/bin" ]; then
	export PATH="$HOME/.nix-profile/bin:$PATH"
fi

# Add ~/.local/bin to PATH (for rebuild, generate-machine-config, etc.
# deployed by the scripts group which is deployed before nix)
if [ -d "$HOME/.local/bin" ]; then
	export PATH="$HOME/.local/bin:$PATH"
fi

# nix-darwin activation refuses to overwrite /etc files it doesn't manage.
# Rename any conflicting files so the first darwin-rebuild switch succeeds.
if [[ "$OSTYPE" == "darwin"* ]]; then
	for f in /etc/zshenv /etc/zshrc /etc/bashrc /etc/zprofile; do
		if [ -f "$f" ] && [ ! -L "$f" ]; then
			echo "Renaming $f → ${f}.before-nix-darwin"
			sudo mv "$f" "${f}.before-nix-darwin"
		fi
	done
fi

# ---------------------------------------------------------------------------
# Resolve nix config directory (follow symlinks)
# ---------------------------------------------------------------------------
NIX_CONFIG_DIR="$(readlink -f "$HOME/.config/nix" 2>/dev/null || echo "$HOME/.config/nix")"
MACHINE_NIX="$NIX_CONFIG_DIR/machine.nix"

# ---------------------------------------------------------------------------
# Configure GitHub access token (avoid API rate limits in CI)
# ---------------------------------------------------------------------------
USER_NIX_CONF="$HOME/.config/nix/nix.conf"
if [ -n "${GITHUB_TOKEN:-}" ]; then
	mkdir -p "$(dirname "$USER_NIX_CONF")"
	if [ ! -f "$USER_NIX_CONF" ] || ! grep -q "access-tokens" "$USER_NIX_CONF"; then
		echo "access-tokens = github.com=$GITHUB_TOKEN" >>"$USER_NIX_CONF"
		echo "Configured GitHub access token for nix"
	fi
fi

# ---------------------------------------------------------------------------
# Generate machine.nix if missing
# ---------------------------------------------------------------------------
if [ ! -f "$MACHINE_NIX" ]; then
	echo "machine.nix not found at: $MACHINE_NIX"
	echo "Auto-generating machine configuration..."

	USERNAME="${USER:-$(whoami)}"

	# Detect architecture (normalize arm64 → aarch64)
	RAW_ARCH="$(uname -m)"
	case "$RAW_ARCH" in
	arm64 | aarch64) ARCH="aarch64" ;;
	x86_64) ARCH="x86_64" ;;
	*) echo "Unsupported architecture: $RAW_ARCH" && exit 1 ;;
	esac

	# Detect OS
	RAW_OS="$(uname -s)"
	case "$RAW_OS" in
	Darwin) NIX_OS="darwin" ;;
	*) NIX_OS="linux" ;;
	esac

	SYSTEM="${ARCH}-${NIX_OS}"

	# Detect hostname
	if [ "$NIX_OS" = "darwin" ]; then
		HOSTNAME="$(scutil --get ComputerName 2>/dev/null || hostname -s)"
	else
		HOSTNAME="$(hostname -s 2>/dev/null || hostname)"
	fi

	mkdir -p "$NIX_CONFIG_DIR"
	cat >"$MACHINE_NIX" <<-ENDMACHINE
		# Machine-specific configuration
		# Auto-generated by nix post-hook
		# This file is gitignored and will not be committed
		{
		  # Your username on this machine
		  username = "$USERNAME";

		  # System architecture
		  system = "$SYSTEM";

		  # Machine hostname
		  hostname = "$HOSTNAME";
		}
	ENDMACHINE

	echo "Created machine.nix  Username=$USERNAME  System=$SYSTEM  Hostname=$HOSTNAME"
fi

# ---------------------------------------------------------------------------
# Parse machine.nix — extract username and system via grep/sed
# ---------------------------------------------------------------------------
CFG_USERNAME="$(grep 'username = ' "$MACHINE_NIX" | sed 's/.*"\([^"]*\)".*/\1/')"
CFG_SYSTEM="$(grep 'system = ' "$MACHINE_NIX" | sed 's/.*"\([^"]*\)".*/\1/')"

if [ -z "$CFG_USERNAME" ] || [ -z "$CFG_SYSTEM" ]; then
	echo "ERROR: Failed to read username or system from machine.nix"
	exit 1
fi

echo "Configuration:  Username=$CFG_USERNAME  System=$CFG_SYSTEM"

# ---------------------------------------------------------------------------
# Detect root-only nix (Docker/containers without systemd)
# ---------------------------------------------------------------------------
ROOT_ONLY_NIX=false
if [ ! -d "/run/systemd/system" ] && [ ! -S "/nix/var/nix/daemon-socket/socket" ] && [ "$(id -u)" != "0" ]; then
	ROOT_ONLY_NIX=true
fi

SUDO_PREFIX=""
if [ "$ROOT_ONLY_NIX" = true ]; then
	SUDO_PREFIX="sudo"
fi

# ---------------------------------------------------------------------------
# Rebuild
# ---------------------------------------------------------------------------
if [[ "$OSTYPE" == "darwin"* ]]; then
	# Back up /etc/shells before nix-darwin takes ownership (one-time)
	if [ -f /etc/shells ] && [ ! -f /etc/shells.before-nix-darwin ]; then
		echo "Backing up /etc/shells to /etc/shells.before-nix-darwin"
		sudo cp /etc/shells /etc/shells.before-nix-darwin
	fi

	# Build darwin-rebuild command (with nix run fallback for first-time setup)
	if command -v darwin-rebuild &>/dev/null; then
		DARWIN_CMD="darwin-rebuild switch --flake '${NIX_CONFIG_DIR}#default' --impure"
	else
		echo "darwin-rebuild not found, using nix run for first-time setup..."
		DARWIN_CMD="nix run nix-darwin/master -- switch --flake '${NIX_CONFIG_DIR}#default' --impure"
	fi

	REBUILD_CMD="ulimit -n 10240 && sudo NIX_USER_CONFIG_DIR='${NIX_CONFIG_DIR}' ${DARWIN_CMD}"
	echo "Running: $REBUILD_CMD"
	bash -c "$REBUILD_CMD"
	echo "Configuration rebuilt successfully! (darwin + home-manager)"
else
	# Linux: standalone home-manager switch
	HM_FLAKE="${NIX_CONFIG_DIR}#${CFG_USERNAME}@${CFG_SYSTEM}"

	if command -v home-manager &>/dev/null; then
		HM_CMD="home-manager switch --flake '${HM_FLAKE}' --impure"
	else
		echo "home-manager not found, using nix run for first-time setup..."
		HM_CMD="nix run home-manager -- switch --flake '${HM_FLAKE}' --impure"
	fi

	REBUILD_CMD="${SUDO_PREFIX} USER=${CFG_USERNAME} HOME=${HOME} NIX_USER_CONFIG_DIR='${NIX_CONFIG_DIR}' ${HM_CMD}"
	echo "Running: $REBUILD_CMD"
	bash -c "$REBUILD_CMD"
	echo "Configuration rebuilt successfully! (home-manager)"
fi

# ---------------------------------------------------------------------------
# Post-rebuild: add profile paths so newly installed tools are found
# ---------------------------------------------------------------------------
for p in \
	"/etc/profiles/per-user/${USER:-$(whoami)}/bin" \
	"$HOME/.local/state/nix/profiles/home-manager/home-path/bin" \
	"/run/current-system/sw/bin"; do
	if [ -d "$p" ]; then
		export PATH="$p:$PATH"
	fi
done

# Install raco fmt package (needed by dprint for .scm files).
if command -v raco &>/dev/null; then
	echo "Installing raco fmt package..."
	raco pkg install --skip-installed --auto --scope user fmt || echo "Warning: raco pkg install fmt failed"
else
	echo "Warning: raco not found after rebuild, skipping fmt package install"
fi

# After rebuild, make home-manager packages available to subsequent CI steps.
if [ -n "${GITHUB_ACTIONS:-}" ] && [ -n "${GITHUB_PATH:-}" ]; then
	HM_PROFILE="$HOME/.local/state/nix/profiles/home-manager/home-path/bin"
	if [ -d "$HM_PROFILE" ]; then
		echo "$HM_PROFILE" >>"$GITHUB_PATH"
		echo "Added home-manager profile to GITHUB_PATH: $HM_PROFILE"
	fi

	# Also source hm-session-vars.sh if available (sets HOME_MANAGER_VARS, etc.)
	if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
		# shellcheck disable=SC1091
		. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
	fi
fi
